#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# #
#   @project        TVApp2
#   @usage          Automatic m3u and xml guide updater for TheTvApp, TVPass, and MoveOnJoy utilized within your IPTV client.
#   @file           run
#   @repo.1         https://github.com/iFlip721/tvapp2
#   @repo.2         https://github.com/Aetherinox/tvapp2
#   @repo.3         https://git.binaryninja.net/pub_projects/tvapp2
#   @repo.alpine    https://github.com/Aetherinox/docker-base-alpine
# #
